version: "3"
services:
  site: 
    build:
      dockerfile: ./php-dockerfile
      context: .
    ports:
      - 8080:80
    volumes:
      - ./public_html:/var/www/html
  database:
    image: mysql:8
    ports:
      - 5050:3306
    environment:
      MYSQL_DATABASE: blog_db_name
      MYSQL_ROOT_PASSWORD: blog_db_password
      MYSQL_HOST: 0.0.0.0